Vagrant.configure("2") do |config|

  config.vm.box = "autodoria_ubuntu"

  config.vm.synced_folder "./data", "/vagrant"

  config.vm.network "private_network", ip: "192.168.56.210",

    name: "VirtualBox Host-Only Ethernet Adapter"

  config.vm.provider "virtualbox" do |vb|

     vb.memory = "1024"

     vb.cpus = "1"

  end

  config.vm.boot_timeout = 800
  
  config.ssh.username = "autodoria"

  config.ssh.private_key_path = "../ssh/priv_cyber_openssh"

end
