Vagrant.configure("2") do |config|

  config.vm.box = "autodoria_ubuntu"

  config.vm.synced_folder "./data", "/vagrant"

  config.vm.network "private_network", ip: "192.168.56.210",

    name: "VirtualBox Host-Only Ethernet Adapter"

  config.vm.provider "virtualbox" do |vb|

     vb.memory = "1024"

     vb.cpus = "1"

  end

  config.vm.boot_timeout = 800
  
  config.vm.provision "ansible" do |ansible|
     
    ansible.inventory_path = "../ansible/inventory"
   
    ansible.playbook = "../ansible/playbook.yml"
 
  end

end
